name: 'Publish DockerHub'

on:
  workflow_dispatch:
    inputs:
      versionname:
        description: 'Version'
        required: true
        default: '1.63.4'
        type: string

jobs:
  publish-to-docker-hub:
    name: Publish to DockerHub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to DockerHub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build
        uses: docker/build-push-action@v5.1.0
        with:
          context: ./docker/images/n8n
          build-args: |
            N8N_VERSION=${{ inputs.versionname }}
          platforms: linux/amd64,linux/arm64
          provenance: false
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/n8n:${{ inputs.versionname }}
            ${{ secrets.DOCKER_USERNAME }}/n8n:lastest
            ghcr.io/${{ github.repository_owner }}/n8n:${{ inputs.versionname }}
            ghcr.io/${{ github.repository_owner }}/n8n:latest

name: 'Publish DockerHub'

on:
  workflow_dispatch:
    inputs:
      versionname:
        description: 'Version'
        required: true
        default: '1.63.4'
        type: string

jobs:
  publish-to-docker-hub:
    name: Publish to DockerHub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to DockerHub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build
        uses: docker/build-push-action@v5.1.0
        with:
          context: ./docker/images/n8n
          build-args: |
            N8N_VERSION=${{ inputs.versionname }}
          platforms: linux/amd64,linux/arm64
          provenance: false
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/n8n:${{ inputs.versionname }}
            ${{ secrets.DOCKER_USERNAME }}/n8n:lastest
            ghcr.io/${{ github.repository_owner }}/n8n:${{ inputs.versionname }}
            ghcr.io/${{ github.repository_owner }}/n8n:latest
